In [176]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

import random
import decimal

In [205]:
max_hidden_layers = 9
max_neurons_per_layer = 100
min_learning_rate = .0001
max_learning_rate = .01

In [206]:
iris_data = load_iris()

print('Example Data:')
print(iris_data.data[:5])
print('Example Labels:')
print(iris_data.target[:5])

Example Data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example Labels:
[0 0 0 0 0]


In [207]:
x = iris_data.data
y_ = iris_data.target.reshape(-1,1)

encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)

In [208]:
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=.20)

In [217]:
num_hidden_layers = randint(0, max_hidden_layers)
i = 0
print(num_hidden_layers)
model = Sequential()
model.add(Dense(10, input_shape=(4,), activation='relu', name='input'))
while i < num_layers:
    name = 'hidden'+str(i)
    num_neurons = randint(1, max_neurons_per_layer)
    model.add(Dense(num_neurons, activation='relu', name=name))
    i = i+1
model.add(Dense(3, activation='softmax', name='output'))

7


In [218]:
learning_rate = random.uniform(min_learning_rate, max_learning_rate)
print(learning_rate)
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

0.00757121528899


In [219]:
print('Neural Net Model Summary: ')
print(model.summary())

Neural Net Model Summary: 
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (Dense)                (None, 10)                50        
_________________________________________________________________
hidden0 (Dense)              (None, 62)                682       
_________________________________________________________________
hidden1 (Dense)              (None, 3)                 189       
_________________________________________________________________
hidden2 (Dense)              (None, 85)                340       
_________________________________________________________________
hidden3 (Dense)              (None, 44)                3784      
_________________________________________________________________
hidden4 (Dense)              (None, 60)                2700      
_________________________________________________________________
hidden5 (Dense)              (None, 49)          

In [220]:
model.fit(train_x, train_y, verbose = 2, batch_size = 5, epochs = 200)

Epoch 1/200
 - 1s - loss: 1.0637 - acc: 0.5417
Epoch 2/200
 - 0s - loss: 0.6511 - acc: 0.8000
Epoch 3/200
 - 0s - loss: 0.2794 - acc: 0.8833
Epoch 4/200
 - 0s - loss: 0.2144 - acc: 0.9167
Epoch 5/200
 - 0s - loss: 0.1569 - acc: 0.9500
Epoch 6/200
 - 0s - loss: 0.4310 - acc: 0.8167
Epoch 7/200
 - 0s - loss: 0.2590 - acc: 0.9083
Epoch 8/200
 - 0s - loss: 0.1593 - acc: 0.9500
Epoch 9/200
 - 0s - loss: 0.0998 - acc: 0.9583
Epoch 10/200
 - 0s - loss: 0.1142 - acc: 0.9583
Epoch 11/200
 - 0s - loss: 0.2948 - acc: 0.8917
Epoch 12/200
 - 0s - loss: 0.1183 - acc: 0.9750
Epoch 13/200
 - 0s - loss: 0.1101 - acc: 0.9583
Epoch 14/200
 - 0s - loss: 0.1464 - acc: 0.9417
Epoch 15/200
 - 0s - loss: 0.1729 - acc: 0.9417
Epoch 16/200
 - 0s - loss: 0.1406 - acc: 0.9417
Epoch 17/200
 - 0s - loss: 0.1439 - acc: 0.9417
Epoch 18/200
 - 0s - loss: 0.0721 - acc: 0.9833
Epoch 19/200
 - 0s - loss: 0.0644 - acc: 0.9833
Epoch 20/200
 - 0s - loss: 0.1153 - acc: 0.9583
Epoch 21/200
 - 0s - loss: 0.1369 - acc: 0.9417
E

Epoch 171/200
 - 0s - loss: 0.0438 - acc: 0.9917
Epoch 172/200
 - 0s - loss: 0.0425 - acc: 0.9917
Epoch 173/200
 - 0s - loss: 0.0270 - acc: 0.9917
Epoch 174/200
 - 0s - loss: 0.0343 - acc: 0.9917
Epoch 175/200
 - 0s - loss: 0.0338 - acc: 0.9917
Epoch 176/200
 - 0s - loss: 0.0317 - acc: 0.9917
Epoch 177/200
 - 0s - loss: 0.0316 - acc: 0.9917
Epoch 178/200
 - 0s - loss: 0.0328 - acc: 0.9917
Epoch 179/200
 - 0s - loss: 0.0296 - acc: 0.9917
Epoch 180/200
 - 0s - loss: 0.0331 - acc: 0.9917
Epoch 181/200
 - 0s - loss: 0.0301 - acc: 0.9917
Epoch 182/200
 - 0s - loss: 0.0324 - acc: 0.9917
Epoch 183/200
 - 0s - loss: 0.0312 - acc: 0.9917
Epoch 184/200
 - 0s - loss: 0.0324 - acc: 0.9917
Epoch 185/200
 - 0s - loss: 0.0300 - acc: 0.9917
Epoch 186/200
 - 0s - loss: 0.0332 - acc: 0.9917
Epoch 187/200
 - 0s - loss: 0.0287 - acc: 0.9917
Epoch 188/200
 - 0s - loss: 0.0307 - acc: 0.9917
Epoch 189/200
 - 0s - loss: 0.0293 - acc: 0.9917
Epoch 190/200
 - 0s - loss: 0.0670 - acc: 0.9917
Epoch 191/200
 - 0s 

In [221]:
results = model.evaluate(test_x, test_y)

30/30 [==============================] - 0s 8ms/step


In [222]:
print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Final test set loss: 0.304849
Final test set accuracy: 0.900000


In [223]:
question = np.matrix([[5.1,3.5,1.4,0.2]])
print(question)
model.predict(question)

[[5.1 3.5 1.4 0.2]]


array([[1.00000e+00, 8.22531e-11, 2.48845e-21]], dtype=float32)