In [22]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

from collections import OrderedDict
from random import randint
import random
import decimal
from operator import add

In [37]:
max_hidden_layers = 9
max_neurons_per_layer = 100
min_learning_rate = .0001
max_learning_rate = .01
acti_func = ["softmax", "elu", "selu", "softplus", "softsign", 
             "relu", "tanh", "sigmoid", "hard_sigmoid", "linear"]
num_individuals = 16
loss_weight = 10
accuracy_weight = 10
time_weight = 10

In [38]:
def load_data():
    iris_data = load_iris()
    print('Example Data:')
    print(iris_data.data[:5])
    print('Example Labels:')
    print(iris_data.target[:5])
    global iris_data

<ipython-input-38-11c664384486>:7: SyntaxWarning: name 'iris_data' is assigned to before global declaration
  global iris_data


In [39]:
def process_data():
    x = iris_data.data
    y_ = iris_data.target.reshape(-1,1)

    encoder = OneHotEncoder(sparse=False)
    y = encoder.fit_transform(y_)
    train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=.20)
    global train_x, test_x, train_y, test_y

<ipython-input-39-1082ec30e327>:8: SyntaxWarning: name 'train_x' is assigned to before global declaration
  global train_x, test_x, train_y, test_y
<ipython-input-39-1082ec30e327>:8: SyntaxWarning: name 'test_x' is assigned to before global declaration
  global train_x, test_x, train_y, test_y
<ipython-input-39-1082ec30e327>:8: SyntaxWarning: name 'train_y' is assigned to before global declaration
  global train_x, test_x, train_y, test_y
<ipython-input-39-1082ec30e327>:8: SyntaxWarning: name 'test_y' is assigned to before global declaration
  global train_x, test_x, train_y, test_y


In [40]:
load_data()
process_data()

Example Data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example Labels:
[0 0 0 0 0]


In [41]:
def create_network(model_num):
    model_name = "Model"+str(model_num)
    model_desc = {'name':model_name}
    print(model_name)
    model_name = Sequential()
    num_hidden_layers = randint(0, max_hidden_layers)
    i = 0
    model_name.add(Dense(10, input_shape=(4,), activation='relu', name='input'))
    while i < num_hidden_layers:
        name = 'hidden'+str(i)
        num_neurons = randint(1, max_neurons_per_layer)
        activation = acti_func[randint(0, len(acti_func)-1)]
        model_desc.update({'hidden'+str(i) : (num_neurons, activation)})
        #print(activation)
        model_name.add(Dense(num_neurons, activation=activation, name=name))
        i = i+1
    model_name.add(Dense(3, activation='softmax', name='output'))
    global model_name
    global model_desc

<ipython-input-41-0e67b9f64f4e>:18: SyntaxWarning: name 'model_name' is assigned to before global declaration
  global model_name
<ipython-input-41-0e67b9f64f4e>:19: SyntaxWarning: name 'model_desc' is assigned to before global declaration
  global model_desc


In [42]:
def lr_and_optimizer(model_name):
    learning_rate = random.uniform(min_learning_rate, max_learning_rate)
    #print(learning_rate)
    model_desc.update({'learning_rate' : learning_rate})
    optimizer = Adam(lr=learning_rate)
    model_desc.update({'optimizer' : 'Adam'})
    model_name.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [43]:
def print_summary(model_name):
    print('Neural Net Model Summary: ')
    print(model_name.summary())

In [44]:
def train_and_test(model_name):
    model_name.fit(train_x, train_y, verbose = 2, batch_size = 5, epochs = 200)
    results = model_name.evaluate(test_x, test_y)
    global results

<ipython-input-44-915b75c55b69>:4: SyntaxWarning: name 'results' is assigned to before global declaration
  global results


In [45]:
def individual(model_num):
    create_network(model_num)
    #print_summary(model_name)
    lr_and_optimizer(model_name)
    train_and_test(model_name)
    loss_fitness =  (1/float(results[0]))*loss_weight
    acc_fitness = float(results[1])*accuracy_weight
    total_fitness = loss_fitness + acc_fitness
    model_desc.update({'loss_fitness':loss_fitness})
    model_desc.update({'accuracy_fitness':acc_fitness})
    model_desc.update({'total_fitness':total_fitness})
    print(model_name)
    print(model_desc)

In [46]:
def population():
    population_desc = []
    for x in xrange(num_individuals):
        individual(model_num = x)
        population_desc.append(model_desc)
    print(population_desc)
    global population_desc

<ipython-input-46-662326261e74>:7: SyntaxWarning: name 'population_desc' is assigned to before global declaration
  global population_desc


In [47]:
population()

Model0
Epoch 1/200
 - 0s - loss: 0.7524 - acc: 0.6667
Epoch 2/200
 - 0s - loss: 0.3222 - acc: 0.8750
Epoch 3/200
 - 0s - loss: 0.1904 - acc: 0.9333
Epoch 4/200
 - 0s - loss: 0.1607 - acc: 0.9667
Epoch 5/200
 - 0s - loss: 0.5010 - acc: 0.8583
Epoch 6/200
 - 0s - loss: 0.2315 - acc: 0.9000
Epoch 7/200
 - 0s - loss: 0.1377 - acc: 0.9500
Epoch 8/200
 - 0s - loss: 0.1965 - acc: 0.9167
Epoch 9/200
 - 0s - loss: 0.1555 - acc: 0.9417
Epoch 10/200
 - 0s - loss: 0.1874 - acc: 0.9333
Epoch 11/200
 - 0s - loss: 0.1302 - acc: 0.9417
Epoch 12/200
 - 0s - loss: 0.1934 - acc: 0.9417
Epoch 13/200
 - 0s - loss: 0.2175 - acc: 0.9000
Epoch 14/200
 - 0s - loss: 0.1498 - acc: 0.9583
Epoch 15/200
 - 0s - loss: 0.1131 - acc: 0.9500
Epoch 16/200
 - 0s - loss: 0.1348 - acc: 0.9500
Epoch 17/200
 - 0s - loss: 0.1244 - acc: 0.9500
Epoch 18/200
 - 0s - loss: 0.0861 - acc: 0.9583
Epoch 19/200
 - 0s - loss: 0.2165 - acc: 0.9333
Epoch 20/200
 - 0s - loss: 0.1355 - acc: 0.9500
Epoch 21/200
 - 0s - loss: 0.1014 - acc: 0

 - 0s - loss: 0.0589 - acc: 0.9833
Epoch 171/200
 - 0s - loss: 0.0938 - acc: 0.9667
Epoch 172/200
 - 0s - loss: 0.0692 - acc: 0.9833
Epoch 173/200
 - 0s - loss: 0.1990 - acc: 0.9000
Epoch 174/200
 - 0s - loss: 0.0776 - acc: 0.9583
Epoch 175/200
 - 0s - loss: 0.0911 - acc: 0.9500
Epoch 176/200
 - 0s - loss: 0.0960 - acc: 0.9667
Epoch 177/200
 - 0s - loss: 0.0764 - acc: 0.9667
Epoch 178/200
 - 0s - loss: 0.0886 - acc: 0.9833
Epoch 179/200
 - 0s - loss: 0.1111 - acc: 0.9667
Epoch 180/200
 - 0s - loss: 0.0850 - acc: 0.9667
Epoch 181/200
 - 0s - loss: 0.1010 - acc: 0.9583
Epoch 182/200
 - 0s - loss: 0.1711 - acc: 0.9583
Epoch 183/200
 - 0s - loss: 0.1234 - acc: 0.9417
Epoch 184/200
 - 0s - loss: 0.0813 - acc: 0.9750
Epoch 185/200
 - 0s - loss: 0.0619 - acc: 0.9750
Epoch 186/200
 - 0s - loss: 0.0871 - acc: 0.9667
Epoch 187/200
 - 0s - loss: 0.0705 - acc: 0.9667
Epoch 188/200
 - 0s - loss: 0.0627 - acc: 0.9833
Epoch 189/200
 - 0s - loss: 0.0916 - acc: 0.9583
Epoch 190/200
 - 0s - loss: 0.1714

Epoch 132/200
 - 0s - loss: 0.4595 - acc: 0.7083
Epoch 133/200
 - 0s - loss: 0.4667 - acc: 0.6583
Epoch 134/200
 - 0s - loss: 0.4650 - acc: 0.6750
Epoch 135/200
 - 0s - loss: 0.4690 - acc: 0.6167
Epoch 136/200
 - 0s - loss: 0.4646 - acc: 0.6750
Epoch 137/200
 - 0s - loss: 0.4669 - acc: 0.6417
Epoch 138/200
 - 0s - loss: 0.4648 - acc: 0.6000
Epoch 139/200
 - 0s - loss: 0.4723 - acc: 0.6750
Epoch 140/200
 - 0s - loss: 0.4632 - acc: 0.6667
Epoch 141/200
 - 0s - loss: 0.4706 - acc: 0.6333
Epoch 142/200
 - 0s - loss: 0.4652 - acc: 0.6417
Epoch 143/200
 - 0s - loss: 0.4668 - acc: 0.6500
Epoch 144/200
 - 0s - loss: 0.4770 - acc: 0.6417
Epoch 145/200
 - 0s - loss: 0.4724 - acc: 0.5917
Epoch 146/200
 - 0s - loss: 0.4651 - acc: 0.6667
Epoch 147/200
 - 0s - loss: 0.4697 - acc: 0.6250
Epoch 148/200
 - 0s - loss: 0.4685 - acc: 0.6083
Epoch 149/200
 - 0s - loss: 0.4640 - acc: 0.6583
Epoch 150/200
 - 0s - loss: 0.4675 - acc: 0.6750
Epoch 151/200
 - 0s - loss: 0.4643 - acc: 0.6583
Epoch 152/200
 - 0s 

 - 0s - loss: 0.4687 - acc: 0.6750
Epoch 91/200
 - 0s - loss: 0.4674 - acc: 0.6500
Epoch 92/200
 - 0s - loss: 0.4659 - acc: 0.6667
Epoch 93/200
 - 0s - loss: 0.4661 - acc: 0.6417
Epoch 94/200
 - 0s - loss: 0.4646 - acc: 0.6333
Epoch 95/200
 - 0s - loss: 0.4696 - acc: 0.6750
Epoch 96/200
 - 0s - loss: 0.4635 - acc: 0.6750
Epoch 97/200
 - 0s - loss: 0.4663 - acc: 0.6667
Epoch 98/200
 - 0s - loss: 0.4666 - acc: 0.6250
Epoch 99/200
 - 0s - loss: 0.4636 - acc: 0.6750
Epoch 100/200
 - 0s - loss: 0.4634 - acc: 0.6750
Epoch 101/200
 - 0s - loss: 0.4630 - acc: 0.6750
Epoch 102/200
 - 0s - loss: 0.4631 - acc: 0.6417
Epoch 103/200
 - 0s - loss: 0.4636 - acc: 0.6333
Epoch 104/200
 - 0s - loss: 0.4665 - acc: 0.6750
Epoch 105/200
 - 0s - loss: 0.4645 - acc: 0.6500
Epoch 106/200
 - 0s - loss: 0.4660 - acc: 0.6500
Epoch 107/200
 - 0s - loss: 0.4660 - acc: 0.6750
Epoch 108/200
 - 0s - loss: 0.4647 - acc: 0.6250
Epoch 109/200
 - 0s - loss: 0.4641 - acc: 0.6667
Epoch 110/200
 - 0s - loss: 0.4678 - acc: 0

Epoch 49/200
 - 0s - loss: 0.0458 - acc: 0.9917
Epoch 50/200
 - 0s - loss: 0.1153 - acc: 0.9667
Epoch 51/200
 - 0s - loss: 0.1386 - acc: 0.9500
Epoch 52/200
 - 0s - loss: 0.0970 - acc: 0.9583
Epoch 53/200
 - 0s - loss: 0.0920 - acc: 0.9667
Epoch 54/200
 - 0s - loss: 0.1054 - acc: 0.9417
Epoch 55/200
 - 0s - loss: 0.1307 - acc: 0.9583
Epoch 56/200
 - 0s - loss: 0.0967 - acc: 0.9667
Epoch 57/200
 - 0s - loss: 0.1569 - acc: 0.9500
Epoch 58/200
 - 0s - loss: 0.0571 - acc: 0.9833
Epoch 59/200
 - 0s - loss: 0.2587 - acc: 0.9333
Epoch 60/200
 - 0s - loss: 0.1814 - acc: 0.9500
Epoch 61/200
 - 0s - loss: 0.0996 - acc: 0.9833
Epoch 62/200
 - 0s - loss: 0.0810 - acc: 0.9667
Epoch 63/200
 - 0s - loss: 0.0910 - acc: 0.9667
Epoch 64/200
 - 0s - loss: 0.0770 - acc: 0.9750
Epoch 65/200
 - 0s - loss: 0.0610 - acc: 0.9917
Epoch 66/200
 - 0s - loss: 0.1784 - acc: 0.9583
Epoch 67/200
 - 0s - loss: 0.1740 - acc: 0.9500
Epoch 68/200
 - 0s - loss: 0.1099 - acc: 0.9583
Epoch 69/200
 - 0s - loss: 0.1810 - acc:

Epoch 7/200
 - 0s - loss: 0.3509 - acc: 0.9333
Epoch 8/200
 - 0s - loss: 0.3230 - acc: 0.8583
Epoch 9/200
 - 0s - loss: 0.3172 - acc: 0.8833
Epoch 10/200
 - 0s - loss: 0.2661 - acc: 0.9500
Epoch 11/200
 - 0s - loss: 0.2730 - acc: 0.8917
Epoch 12/200
 - 0s - loss: 0.2419 - acc: 0.9417
Epoch 13/200
 - 0s - loss: 0.2153 - acc: 0.9583
Epoch 14/200
 - 0s - loss: 0.2250 - acc: 0.9500
Epoch 15/200
 - 0s - loss: 0.1867 - acc: 0.9500
Epoch 16/200
 - 0s - loss: 0.1873 - acc: 0.9417
Epoch 17/200
 - 0s - loss: 0.1860 - acc: 0.9250
Epoch 18/200
 - 0s - loss: 0.1596 - acc: 0.9500
Epoch 19/200
 - 0s - loss: 0.1468 - acc: 0.9583
Epoch 20/200
 - 0s - loss: 0.1306 - acc: 0.9833
Epoch 21/200
 - 0s - loss: 0.1335 - acc: 0.9667
Epoch 22/200
 - 0s - loss: 0.1336 - acc: 0.9583
Epoch 23/200
 - 0s - loss: 0.1474 - acc: 0.9500
Epoch 24/200
 - 0s - loss: 0.1137 - acc: 0.9833
Epoch 25/200
 - 0s - loss: 0.0900 - acc: 0.9833
Epoch 26/200
 - 0s - loss: 0.1351 - acc: 0.9333
Epoch 27/200
 - 0s - loss: 0.1029 - acc: 0.

 - 0s - loss: 0.0719 - acc: 0.9750
Epoch 177/200
 - 0s - loss: 0.0482 - acc: 0.9833
Epoch 178/200
 - 0s - loss: 0.0939 - acc: 0.9750
Epoch 179/200
 - 0s - loss: 0.0614 - acc: 0.9833
Epoch 180/200
 - 0s - loss: 0.0871 - acc: 0.9667
Epoch 181/200
 - 0s - loss: 0.0922 - acc: 0.9583
Epoch 182/200
 - 0s - loss: 0.0573 - acc: 0.9833
Epoch 183/200
 - 0s - loss: 0.0534 - acc: 0.9750
Epoch 184/200
 - 0s - loss: 0.0783 - acc: 0.9583
Epoch 185/200
 - 0s - loss: 0.0582 - acc: 0.9750
Epoch 186/200
 - 0s - loss: 0.0870 - acc: 0.9750
Epoch 187/200
 - 0s - loss: 0.0759 - acc: 0.9750
Epoch 188/200
 - 0s - loss: 0.0404 - acc: 0.9750
Epoch 189/200
 - 0s - loss: 0.0906 - acc: 0.9583
Epoch 190/200
 - 0s - loss: 0.0486 - acc: 0.9750
Epoch 191/200
 - 0s - loss: 0.0804 - acc: 0.9667
Epoch 192/200
 - 0s - loss: 0.0572 - acc: 0.9833
Epoch 193/200
 - 0s - loss: 0.0732 - acc: 0.9667
Epoch 194/200
 - 0s - loss: 0.0954 - acc: 0.9500
Epoch 195/200
 - 0s - loss: 0.0680 - acc: 0.9667
Epoch 196/200
 - 0s - loss: 0.0584

Epoch 140/200
 - 0s - loss: 0.0808 - acc: 0.9583
Epoch 141/200
 - 0s - loss: 0.0760 - acc: 0.9667
Epoch 142/200
 - 0s - loss: 0.0763 - acc: 0.9667
Epoch 143/200
 - 0s - loss: 0.0511 - acc: 0.9833
Epoch 144/200
 - 0s - loss: 0.1834 - acc: 0.9333
Epoch 145/200
 - 0s - loss: 0.1644 - acc: 0.9250
Epoch 146/200
 - 0s - loss: 0.0618 - acc: 0.9833
Epoch 147/200
 - 0s - loss: 0.0511 - acc: 0.9833
Epoch 148/200
 - 0s - loss: 0.0555 - acc: 0.9833
Epoch 149/200
 - 0s - loss: 0.0578 - acc: 0.9917
Epoch 150/200
 - 0s - loss: 0.0562 - acc: 0.9833
Epoch 151/200
 - 0s - loss: 0.0656 - acc: 0.9833
Epoch 152/200
 - 0s - loss: 0.0654 - acc: 0.9833
Epoch 153/200
 - 0s - loss: 0.0568 - acc: 0.9917
Epoch 154/200
 - 0s - loss: 0.0581 - acc: 0.9833
Epoch 155/200
 - 0s - loss: 0.0565 - acc: 0.9750
Epoch 156/200
 - 0s - loss: 0.0727 - acc: 0.9500
Epoch 157/200
 - 0s - loss: 0.2233 - acc: 0.9250
Epoch 158/200
 - 0s - loss: 0.1681 - acc: 0.9417
Epoch 159/200
 - 0s - loss: 0.0609 - acc: 0.9833
Epoch 160/200
 - 0s 

 - 0s - loss: 0.0648 - acc: 0.9833
Epoch 102/200
 - 0s - loss: 0.0806 - acc: 0.9750
Epoch 103/200
 - 0s - loss: 0.1303 - acc: 0.9417
Epoch 104/200
 - 0s - loss: 0.0903 - acc: 0.9583
Epoch 105/200
 - 0s - loss: 0.0655 - acc: 0.9750
Epoch 106/200
 - 0s - loss: 0.0783 - acc: 0.9750
Epoch 107/200
 - 0s - loss: 0.0677 - acc: 0.9833
Epoch 108/200
 - 0s - loss: 0.2424 - acc: 0.9417
Epoch 109/200
 - 0s - loss: 0.1784 - acc: 0.9250
Epoch 110/200
 - 0s - loss: 0.0782 - acc: 0.9833
Epoch 111/200
 - 0s - loss: 0.2099 - acc: 0.9167
Epoch 112/200
 - 0s - loss: 0.0796 - acc: 0.9667
Epoch 113/200
 - 0s - loss: 0.0715 - acc: 0.9667
Epoch 114/200
 - 0s - loss: 0.0527 - acc: 0.9833
Epoch 115/200
 - 0s - loss: 0.0788 - acc: 0.9750
Epoch 116/200
 - 0s - loss: 0.0762 - acc: 0.9667
Epoch 117/200
 - 0s - loss: 0.0532 - acc: 0.9750
Epoch 118/200
 - 0s - loss: 0.1204 - acc: 0.9500
Epoch 119/200
 - 0s - loss: 0.0582 - acc: 0.9667
Epoch 120/200
 - 0s - loss: 0.0981 - acc: 0.9750
Epoch 121/200
 - 0s - loss: 0.0629

 - 0s - loss: 0.4639 - acc: 0.6750
Epoch 60/200
 - 0s - loss: 0.4627 - acc: 0.6750
Epoch 61/200
 - 0s - loss: 0.4628 - acc: 0.6750
Epoch 62/200
 - 0s - loss: 0.4647 - acc: 0.6750
Epoch 63/200
 - 0s - loss: 0.4666 - acc: 0.6083
Epoch 64/200
 - 0s - loss: 0.4644 - acc: 0.6583
Epoch 65/200
 - 0s - loss: 0.4639 - acc: 0.6750
Epoch 66/200
 - 0s - loss: 0.4640 - acc: 0.6167
Epoch 67/200
 - 0s - loss: 0.4646 - acc: 0.6583
Epoch 68/200
 - 0s - loss: 0.4632 - acc: 0.6500
Epoch 69/200
 - 0s - loss: 0.4629 - acc: 0.6750
Epoch 70/200
 - 0s - loss: 0.4636 - acc: 0.6750
Epoch 71/200
 - 0s - loss: 0.4627 - acc: 0.6750
Epoch 72/200
 - 0s - loss: 0.4629 - acc: 0.6750
Epoch 73/200
 - 0s - loss: 0.4629 - acc: 0.6750
Epoch 74/200
 - 0s - loss: 0.4626 - acc: 0.6750
Epoch 75/200
 - 0s - loss: 0.4635 - acc: 0.6167
Epoch 76/200
 - 0s - loss: 0.4654 - acc: 0.6750
Epoch 77/200
 - 0s - loss: 0.4640 - acc: 0.6083
Epoch 78/200
 - 0s - loss: 0.4618 - acc: 0.6750
Epoch 79/200
 - 0s - loss: 0.4649 - acc: 0.6000
Epoch

Epoch 18/200
 - 0s - loss: 0.1000 - acc: 0.9500
Epoch 19/200
 - 0s - loss: 0.1135 - acc: 0.9583
Epoch 20/200
 - 0s - loss: 0.2503 - acc: 0.9000
Epoch 21/200
 - 0s - loss: 0.0995 - acc: 0.9750
Epoch 22/200
 - 0s - loss: 0.0618 - acc: 0.9917
Epoch 23/200
 - 0s - loss: 0.0637 - acc: 0.9833
Epoch 24/200
 - 0s - loss: 0.0702 - acc: 0.9750
Epoch 25/200
 - 0s - loss: 0.0904 - acc: 0.9583
Epoch 26/200
 - 0s - loss: 0.1123 - acc: 0.9500
Epoch 27/200
 - 0s - loss: 0.1668 - acc: 0.9250
Epoch 28/200
 - 0s - loss: 0.0676 - acc: 0.9750
Epoch 29/200
 - 0s - loss: 0.0692 - acc: 0.9667
Epoch 30/200
 - 0s - loss: 0.0668 - acc: 0.9667
Epoch 31/200
 - 0s - loss: 0.0576 - acc: 0.9833
Epoch 32/200
 - 0s - loss: 0.0613 - acc: 0.9667
Epoch 33/200
 - 0s - loss: 0.1048 - acc: 0.9583
Epoch 34/200
 - 0s - loss: 0.0550 - acc: 0.9833
Epoch 35/200
 - 0s - loss: 0.0555 - acc: 0.9833
Epoch 36/200
 - 0s - loss: 0.0477 - acc: 0.9750
Epoch 37/200
 - 0s - loss: 0.1294 - acc: 0.9500
Epoch 38/200
 - 0s - loss: 0.0594 - acc:

Epoch 187/200
 - 0s - loss: 0.0611 - acc: 0.9750
Epoch 188/200
 - 0s - loss: 0.0473 - acc: 0.9833
Epoch 189/200
 - 0s - loss: 0.0580 - acc: 0.9833
Epoch 190/200
 - 0s - loss: 0.0783 - acc: 0.9750
Epoch 191/200
 - 0s - loss: 0.0746 - acc: 0.9667
Epoch 192/200
 - 0s - loss: 0.0520 - acc: 0.9833
Epoch 193/200
 - 0s - loss: 0.0501 - acc: 0.9750
Epoch 194/200
 - 0s - loss: 0.0626 - acc: 0.9750
Epoch 195/200
 - 0s - loss: 0.0478 - acc: 0.9750
Epoch 196/200
 - 0s - loss: 0.0661 - acc: 0.9833
Epoch 197/200
 - 0s - loss: 0.0851 - acc: 0.9667
Epoch 198/200
 - 0s - loss: 0.0686 - acc: 0.9667
Epoch 199/200
 - 0s - loss: 0.0483 - acc: 0.9917
Epoch 200/200
 - 0s - loss: 0.0526 - acc: 0.9833
30/30 [==============================] - 0s 7ms/step
{'hidden2': (4, 'relu'), 'hidden1': (15, 'selu'), 'hidden0': (79, 'softmax'), 'optimizer': 'Adam', 'name': 'Model8', 'learning_rate': 0.0030525906212914558, 'loss_fitness': 114.83291066657688, 'total_fitness': 124.49957705508854, 'accuracy_fitness': 9.666666388

Epoch 149/200
 - 0s - loss: 0.0811 - acc: 0.9750
Epoch 150/200
 - 0s - loss: 0.0484 - acc: 0.9833
Epoch 151/200
 - 0s - loss: 0.0795 - acc: 0.9667
Epoch 152/200
 - 0s - loss: 0.0592 - acc: 0.9750
Epoch 153/200
 - 0s - loss: 0.0772 - acc: 0.9667
Epoch 154/200
 - 0s - loss: 0.0800 - acc: 0.9750
Epoch 155/200
 - 0s - loss: 0.0909 - acc: 0.9667
Epoch 156/200
 - 0s - loss: 0.0837 - acc: 0.9750
Epoch 157/200
 - 0s - loss: 0.1025 - acc: 0.9667
Epoch 158/200
 - 0s - loss: 0.0650 - acc: 0.9917
Epoch 159/200
 - 0s - loss: 0.0658 - acc: 0.9833
Epoch 160/200
 - 0s - loss: 0.0614 - acc: 0.9750
Epoch 161/200
 - 0s - loss: 0.0637 - acc: 0.9750
Epoch 162/200
 - 0s - loss: 0.0497 - acc: 0.9833
Epoch 163/200
 - 0s - loss: 0.0390 - acc: 0.9917
Epoch 164/200
 - 0s - loss: 0.0634 - acc: 0.9750
Epoch 165/200
 - 0s - loss: 0.0476 - acc: 0.9833
Epoch 166/200
 - 0s - loss: 0.1060 - acc: 0.9417
Epoch 167/200
 - 0s - loss: 0.0666 - acc: 0.9667
Epoch 168/200
 - 0s - loss: 0.0580 - acc: 0.9833
Epoch 169/200
 - 0s 

Epoch 111/200
 - 0s - loss: 0.0749 - acc: 0.9750
Epoch 112/200
 - 0s - loss: 0.0503 - acc: 0.9833
Epoch 113/200
 - 0s - loss: 0.0642 - acc: 0.9833
Epoch 114/200
 - 0s - loss: 0.0479 - acc: 0.9917
Epoch 115/200
 - 0s - loss: 0.0516 - acc: 0.9833
Epoch 116/200
 - 0s - loss: 0.0500 - acc: 0.9917
Epoch 117/200
 - 0s - loss: 0.0517 - acc: 0.9833
Epoch 118/200
 - 0s - loss: 0.0457 - acc: 0.9833
Epoch 119/200
 - 0s - loss: 0.0756 - acc: 0.9667
Epoch 120/200
 - 0s - loss: 0.1058 - acc: 0.9583
Epoch 121/200
 - 0s - loss: 0.0595 - acc: 0.9750
Epoch 122/200
 - 0s - loss: 0.0520 - acc: 0.9917
Epoch 123/200
 - 0s - loss: 0.0517 - acc: 0.9833
Epoch 124/200
 - 0s - loss: 0.0617 - acc: 0.9833
Epoch 125/200
 - 0s - loss: 0.0476 - acc: 0.9917
Epoch 126/200
 - 0s - loss: 0.0580 - acc: 0.9833
Epoch 127/200
 - 0s - loss: 0.0991 - acc: 0.9667
Epoch 128/200
 - 0s - loss: 0.0526 - acc: 0.9833
Epoch 129/200
 - 0s - loss: 0.0742 - acc: 0.9667
Epoch 130/200
 - 0s - loss: 0.0440 - acc: 0.9750
Epoch 131/200
 - 0s 

Epoch 71/200
 - 0s - loss: 0.0984 - acc: 0.9500
Epoch 72/200
 - 0s - loss: 0.1180 - acc: 0.9667
Epoch 73/200
 - 0s - loss: 0.0692 - acc: 0.9583
Epoch 74/200
 - 0s - loss: 0.1360 - acc: 0.9417
Epoch 75/200
 - 0s - loss: 0.1250 - acc: 0.9500
Epoch 76/200
 - 0s - loss: 0.1554 - acc: 0.9333
Epoch 77/200
 - 0s - loss: 0.0713 - acc: 0.9750
Epoch 78/200
 - 0s - loss: 0.0702 - acc: 0.9583
Epoch 79/200
 - 0s - loss: 0.1065 - acc: 0.9750
Epoch 80/200
 - 0s - loss: 0.1462 - acc: 0.9500
Epoch 81/200
 - 0s - loss: 0.0688 - acc: 0.9750
Epoch 82/200
 - 0s - loss: 0.0998 - acc: 0.9750
Epoch 83/200
 - 0s - loss: 0.0722 - acc: 0.9500
Epoch 84/200
 - 0s - loss: 0.0955 - acc: 0.9667
Epoch 85/200
 - 0s - loss: 0.1377 - acc: 0.9500
Epoch 86/200
 - 0s - loss: 0.0711 - acc: 0.9583
Epoch 87/200
 - 0s - loss: 0.0601 - acc: 0.9833
Epoch 88/200
 - 0s - loss: 0.0654 - acc: 0.9583
Epoch 89/200
 - 0s - loss: 0.0751 - acc: 0.9750
Epoch 90/200
 - 0s - loss: 0.1297 - acc: 0.9333
Epoch 91/200
 - 0s - loss: 0.1077 - acc:

Epoch 31/200
 - 0s - loss: 0.4714 - acc: 0.6500
Epoch 32/200
 - 0s - loss: 0.5129 - acc: 0.5833
Epoch 33/200
 - 0s - loss: 0.4694 - acc: 0.6667
Epoch 34/200
 - 0s - loss: 0.4705 - acc: 0.6833
Epoch 35/200
 - 0s - loss: 0.4789 - acc: 0.6167
Epoch 36/200
 - 0s - loss: 0.4666 - acc: 0.6583
Epoch 37/200
 - 0s - loss: 0.4295 - acc: 0.8083
Epoch 38/200
 - 0s - loss: 0.4393 - acc: 0.7833
Epoch 39/200
 - 0s - loss: 0.5015 - acc: 0.6833
Epoch 40/200
 - 0s - loss: 0.4776 - acc: 0.7417
Epoch 41/200
 - 0s - loss: 0.4904 - acc: 0.6750
Epoch 42/200
 - 0s - loss: 0.3304 - acc: 0.8500
Epoch 43/200
 - 0s - loss: 0.2218 - acc: 0.9083
Epoch 44/200
 - 0s - loss: 0.2602 - acc: 0.9417
Epoch 45/200
 - 0s - loss: 0.6336 - acc: 0.6333
Epoch 46/200
 - 0s - loss: 0.3954 - acc: 0.8250
Epoch 47/200
 - 0s - loss: 0.1401 - acc: 0.9500
Epoch 48/200
 - 0s - loss: 0.3840 - acc: 0.8500
Epoch 49/200
 - 0s - loss: 0.1482 - acc: 0.9417
Epoch 50/200
 - 0s - loss: 0.3875 - acc: 0.8250
Epoch 51/200
 - 0s - loss: 0.1544 - acc:

Epoch 200/200
 - 0s - loss: 0.4689 - acc: 0.6750
30/30 [==============================] - 0s 9ms/step
{'hidden3': (79, 'relu'), 'hidden2': (22, 'tanh'), 'hidden1': (21, 'tanh'), 'hidden0': (41, 'elu'), 'optimizer': 'Adam', 'name': 'Model12', 'hidden4': (53, 'softsign'), 'learning_rate': 0.007293872636565301, 'loss_fitness': 21.255050416591473, 'accuracy_fitness': 6.333333253860474, 'total_fitness': 27.588383670451947}
Model13
Epoch 1/200
 - 1s - loss: 0.9997 - acc: 0.5083
Epoch 2/200
 - 0s - loss: 0.5422 - acc: 0.8083
Epoch 3/200
 - 0s - loss: 0.3675 - acc: 0.8583
Epoch 4/200
 - 0s - loss: 0.2940 - acc: 0.8750
Epoch 5/200
 - 0s - loss: 0.1752 - acc: 0.9500
Epoch 6/200
 - 0s - loss: 0.1520 - acc: 0.9417
Epoch 7/200
 - 0s - loss: 0.1214 - acc: 0.9583
Epoch 8/200
 - 0s - loss: 0.1153 - acc: 0.9583
Epoch 9/200
 - 0s - loss: 0.1237 - acc: 0.9417
Epoch 10/200
 - 0s - loss: 0.0960 - acc: 0.9667
Epoch 11/200
 - 0s - loss: 0.1223 - acc: 0.9500
Epoch 12/200
 - 0s - loss: 0.1655 - acc: 0.9333
Epo

Epoch 161/200
 - 0s - loss: 0.0737 - acc: 0.9750
Epoch 162/200
 - 0s - loss: 0.0574 - acc: 0.9750
Epoch 163/200
 - 0s - loss: 0.0527 - acc: 0.9750
Epoch 164/200
 - 0s - loss: 0.0813 - acc: 0.9750
Epoch 165/200
 - 0s - loss: 0.0618 - acc: 0.9750
Epoch 166/200
 - 0s - loss: 0.0857 - acc: 0.9583
Epoch 167/200
 - 0s - loss: 0.0599 - acc: 0.9833
Epoch 168/200
 - 0s - loss: 0.0392 - acc: 0.9917
Epoch 169/200
 - 0s - loss: 0.0650 - acc: 0.9667
Epoch 170/200
 - 0s - loss: 0.1172 - acc: 0.9333
Epoch 171/200
 - 0s - loss: 0.0821 - acc: 0.9750
Epoch 172/200
 - 0s - loss: 0.0997 - acc: 0.9583
Epoch 173/200
 - 0s - loss: 0.0530 - acc: 0.9750
Epoch 174/200
 - 0s - loss: 0.0484 - acc: 0.9833
Epoch 175/200
 - 0s - loss: 0.0556 - acc: 0.9833
Epoch 176/200
 - 0s - loss: 0.0437 - acc: 0.9833
Epoch 177/200
 - 0s - loss: 0.0654 - acc: 0.9750
Epoch 178/200
 - 0s - loss: 0.0455 - acc: 0.9833
Epoch 179/200
 - 0s - loss: 0.0456 - acc: 0.9833
Epoch 180/200
 - 0s - loss: 0.0769 - acc: 0.9750
Epoch 181/200
 - 0s 

 - 0s - loss: 0.0728 - acc: 0.9667
Epoch 123/200
 - 0s - loss: 0.0615 - acc: 0.9750
Epoch 124/200
 - 0s - loss: 0.0859 - acc: 0.9583
Epoch 125/200
 - 0s - loss: 0.1460 - acc: 0.9750
Epoch 126/200
 - 0s - loss: 0.0859 - acc: 0.9667
Epoch 127/200
 - 0s - loss: 0.0663 - acc: 0.9833
Epoch 128/200
 - 0s - loss: 0.0558 - acc: 0.9833
Epoch 129/200
 - 0s - loss: 0.0685 - acc: 0.9750
Epoch 130/200
 - 0s - loss: 0.0662 - acc: 0.9750
Epoch 131/200
 - 0s - loss: 0.1442 - acc: 0.9333
Epoch 132/200
 - 0s - loss: 0.6288 - acc: 0.8750
Epoch 133/200
 - 0s - loss: 0.1774 - acc: 0.9417
Epoch 134/200
 - 0s - loss: 0.0676 - acc: 0.9667
Epoch 135/200
 - 0s - loss: 0.1049 - acc: 0.9667
Epoch 136/200
 - 0s - loss: 0.0641 - acc: 0.9750
Epoch 137/200
 - 0s - loss: 0.0877 - acc: 0.9750
Epoch 138/200
 - 0s - loss: 0.1135 - acc: 0.9583
Epoch 139/200
 - 0s - loss: 0.8380 - acc: 0.7500
Epoch 140/200
 - 0s - loss: 0.3132 - acc: 0.8500
Epoch 141/200
 - 0s - loss: 0.2066 - acc: 0.9333
Epoch 142/200
 - 0s - loss: 0.0830

Epoch 83/200
 - 0s - loss: 0.1144 - acc: 0.9667
Epoch 84/200
 - 0s - loss: 0.1220 - acc: 0.9417
Epoch 85/200
 - 0s - loss: 0.0896 - acc: 0.9583
Epoch 86/200
 - 0s - loss: 0.1027 - acc: 0.9583
Epoch 87/200
 - 0s - loss: 0.1067 - acc: 0.9667
Epoch 88/200
 - 0s - loss: 0.1606 - acc: 0.9417
Epoch 89/200
 - 0s - loss: 0.1920 - acc: 0.9417
Epoch 90/200
 - 0s - loss: 0.0777 - acc: 0.9833
Epoch 91/200
 - 0s - loss: 0.0680 - acc: 0.9833
Epoch 92/200
 - 0s - loss: 0.2612 - acc: 0.9000
Epoch 93/200
 - 0s - loss: 0.1037 - acc: 0.9583
Epoch 94/200
 - 0s - loss: 0.0706 - acc: 0.9750
Epoch 95/200
 - 0s - loss: 0.0656 - acc: 0.9667
Epoch 96/200
 - 0s - loss: 0.0407 - acc: 0.9917
Epoch 97/200
 - 0s - loss: 0.0365 - acc: 0.9833
Epoch 98/200
 - 0s - loss: 0.0681 - acc: 0.9750
Epoch 99/200
 - 0s - loss: 0.2346 - acc: 0.9250
Epoch 100/200
 - 0s - loss: 0.1173 - acc: 0.9583
Epoch 101/200
 - 0s - loss: 0.0719 - acc: 0.9667
Epoch 102/200
 - 0s - loss: 0.0512 - acc: 0.9667
Epoch 103/200
 - 0s - loss: 0.0603 - 

In [48]:
def grade():    
    fitness_sum = 0
    'Find average fitness for a population.'
    for x in population_desc:
        fitness_sum = x.get("total_fitness") + fitness_sum
    avg_fitness = fitness_sum/len(population_desc)
    print(avg_fitness)
    global avg_fitness

<ipython-input-48-e0a3493f5de1>:8: SyntaxWarning: name 'avg_fitness' is assigned to before global declaration
  global avg_fitness


In [49]:
grade()

110.601494703


In [72]:
parents = []
for x in population_desc:
    if x.get("total_fitness") >= avg_fitness:
        parents.append(x.get('name'))
        difference = x.get('total_fitness') - avg_fitness
        print(x.get("name")+"    "+str(x.get("total_fitness"))+"    "+str(difference))
print(parents)
if len(parents) % 2 !=0:
    print('odd number')
        

Model0    185.937747585    75.3362528825
Model3    166.777372432    56.1758777289
Model4    179.897631814    69.2961371108
Model5    144.804915601    34.2034208978
Model8    124.499577055    13.8980823522
Model9    121.569745443    10.9682507399
Model10    118.24731882    7.64582411741
Model11    180.372556477    69.7710617745
Model13    171.029426943    60.4279322402
['Model0', 'Model3', 'Model4', 'Model5', 'Model8', 'Model9', 'Model10', 'Model11', 'Model13']
odd number
